package seeds

import (
	"DatingApp/entities"
	"gorm.io/gorm"
)

func SeedUsers(db *gorm.DB) error {
	users := []entities.User{
		entities.User{
			Id:          1,
			Name:        "Budi Hernandez",
			Email:       "budi@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          2,
			Name:        "Steve",
			Email:       "steve@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          3,
			Name:        "Tony",
			Email:       "tony@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          4,
			Name:        "Bruce",
			Email:       "bruce@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          5,
			Name:        "RAFLI ARDIANSYAH",
			Email:       "rafli@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          6,
			Name:        "LISA AMELIA",
			Email:       "lisa@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          7,
			Name:        "YULI VANISA AZZAHRA",
			Email:       "yuli@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          8,
			Name:        "DINA FAZRIAH",
			Email:       "dina@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          9,
			Name:        "WASTINI",
			Email:       "wastini@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          10,
			Name:        "NAURA CALISTA",
			Email:       "naura@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          11,
			Name:        "SAIFUL IKWAN PURWITO",
			Email:       "saiful@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          12,
			Name:        "ALI YAHYA",
			Email:       "ali@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          13,
			Name:        "AFIFA ZAHWA AZZAHRA",
			Email:       "afifa@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          14,
			Name:        "KHANA SALSABILLA ZANATY",
			Email:       "khana@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          15,
			Name:        "ADITYA WARMAN",
			Email:       "aditya@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          16,
			Name:        "MIFFTAVADINE NAOMIASYIFFA",
			Email:       "mifftavadine@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          17,
			Name:        "ALI MUFLIH",
			Email:       "alim@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          18,
			Name:        "MUHAMMAD ABUNK NATAJAYA",
			Email:       "abub@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          19,
			Name:        "JUMRIANI",
			Email:       "jumriani@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          20,
			Name:        "OKTAVIANI SIMBOLOM",
			Email:       "oktaviani@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          21,
			Name:        "ANGELIA VANESA PUTRI",
			Email:       "angela@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          22,
			Name:        "ATHIFAH THAHIRAH",
			Email:       "athifah@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          23,
			Name:        "EVANO DAFFA HILALLAH",
			Email:       "evano@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          24,
			Name:        "ELIZABETH JESSICA MANULLANG",
			Email:       "elizabeth@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          25,
			Name:        "CLEODORA CELESTA SOEHARTONO",
			Email:       "cleodora@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          26,
			Name:        "REGINA MARIA VANESSA KURNIAWAN",
			Email:       "regina@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          27,
			Name:        "BERNADETTE FRISKA WIJAYA",
			Email:       "bernadette@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          28,
			Name:        "NATALIA CHRISTIE",
			Email:       "natalia@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          29,
			Name:        "HELENA KAYLA WONGSO",
			Email:       "helena@mail.com",
			Gender:      "female",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
		entities.User{
			Id:          30,
			Name:        "SISWANTO",
			Email:       "siswanto@mail.com",
			Gender:      "male",
			PhoneNumber: "+62877XXXXXXXX",
			Password:    "$2a$14$QESIH9pqZTyUzogyB0NHVuRCgU1bpIbFjHOLT9XFZSsDW44TKxgqC",
		},
	}

	db.Create(&users)

	return nil
}
